This form documents the artifacts associated with the article (i.e., the data and code supporting the computational findings) and describes how to reproduce the findings.


# Part 1: Data

- [ ] This paper does not involve analysis of external data (i.e., no data are used or the only data are generated by the authors via simulation in their code).

- [x] I certify that the author(s) of the manuscript have legitimate access to and permission to use the data used in this manuscript.

## Abstract

The data we analyze consists of 18,296 adults diagnosed with colon cancer in England in 2012, using data from national population-based cancer registries linked to secondary care records. 

## Availability

- [ ] Data **are** publicly available.
- [x] Data **cannot be made** publicly available.

If the data are publicly available, see the *Publicly available data* section. Otherwise, see the *Non-publicly available data* section, below.

### Publicly available data

- [ ] Data are available online at:

- [ ] Data are available as part of the paper’s supplementary material.

- [ ] Data are publicly available by request, following the process described here:

- [ ] Data are or will be made available through some other mechanism, described here:

### Non-publicly available data

The data used for this study are the English National Cancer Registry data 1971–2016. Cancer registration data consist of patient information and as such, it is protected under the Data Protection Act 1998 and GDPR 2018 and cannot be made available as open data. Formal requests for release of cancer registration data can be made to the data custodian NHS Digital (NHSD). Detailed information on the application process can be found at https://digital.nhs.uk/ndrs/. The authors have obtained the ethical and statutory approvals required for this research (PIAG 1-05(c)/2007); ethical approval updated 6 April 2017 (REC 13/LO/0610).

As an alternative to the real data, we provide code that applies the same methodology to publicly available data on a similar dataset for individuals diagnosed with leukemia, that addresses essentially the same epidemiological questions. An alternative analysis for this dataset is provided in R markdown files in our submission.

Our work is motivated by genuine epidemiological questions, and hence we view the work as important on their own as our results have public health implications.

## Description

### File format(s)

- [ ] CSV or other plain text.
- [x] Software-specific binary format (.Rda, Python pickle, etc.): .rds
- [ ] Standardized binary format (e.g., netCDF, HDF5, etc.): 
- [ ] Other (please specify):

### Data dictionary

- [ ] Provided by authors in the following file(s):
- [ ] Data file(s) is(are) self-describing (e.g., netCDF files)
- [x] Available at the following URL: https://search.r-project.org/CRAN/refmans/spBayesSurv/html/LeukSurv.html

### Additional Information (optional)

# Part 2: Code

## Abstract

We provide a package that fits the proposed methodology along with scripts that reproduce our simulation study and markdown files that perform a related analysis on the `LeukSurv` dataset in the `spBayesSurv` package.

## Description

### Code format(s)

- [x] Script files
    - [x] R
    - [ ] Python
    - [ ] Matlab
    - [ ] Other: 
- [x] Package
    - [x] R
    - [ ] Python
    - [ ] MATLAB toolbox
    - [ ] Other: 
- [x] Reproducible report 
    - [x] R Markdown
    - [ ] Jupyter notebook
    - [ ] Other:
- [ ] Shell script
- [ ] Other (please specify): 

### Supporting software requirements

<!--
Please cite all software packages in the References Section in similar fashion to paper citations, citing packages that are foundational to the research outcome (including packages that implement methods to which you compare your methods). You may elect to not cite packages used for supporting purposes. For R packages, note that running `citation('name_of_package')` often shows how the package authors wish to be cited. 
-->

#### Version of primary software used

R version 4.4.1

#### Libraries and dependencies used by the code

The following R packages are used.

  - zeallot 0.1.0
  - devtools 2.4.5
  - usethis 2.2.3
  - bayestestR 0.15.0
  - PWEXP 0.5.0
  - fastmatch 1.1-4
  - rstan 2.32.6
  - StanHeaders 2.32.10
  - lubridate 1.9.3
  - forcats 1.0.0
  - purrr 1.0.2
  - readr 2.1.5
  - tidyr 1.3.1
  - tibble 3.2.1
  - tidyverse 2.0.0
  - tidybayes 3.0.6
  - survival 3.7-0
  - possum 0.3
  - RColorBrewer 1.1-3
  - dplyr 1.1.4
  - fastDummies 1.7.3
  - stringr 1.5.1
  - ggplot2 3.5.1
  - rpart.plot 3.1.2
  - rpart 4.1.23
  - mgcv 1.9-1
  - nlme 3.1-165
  - spBayesSurv 1.1.8
  - ggdist 3.3.2
  - loo 2.8.0
  - insight 0.20.5
  - rlang 1.1.4

### Supporting system/hardware requirements (optional)

<!--
OPTIONAL: System/hardware requirements including operating system with version number, access to cluster, GPUs, etc.
-->

### Parallelization used

- [ ] No parallel code used
- [x] Multi-core parallelization on a single machine/node
    - Number of cores used: 4
- [ ] Multi-machine/multi-node parallelization 
    - Number of nodes and cores used: 

### License

- [x] MIT License (default)
- [ ] BSD 
- [ ] GPL v3.0
- [ ] Creative Commons
- [ ] Other: (please specify)


### Additional information (optional)

The supplementary material will also be made available at [www.github.com/theodds/RelSurvBart](www.github.com/theodds/RelSurvBart).

# Part 3: Reproducibility workflow

## Scope

The provided workflow reproduces:

- [ ] Any numbers provided in text in the paper
- [x] The computational method(s) presented in the paper (i.e., code is provided that implements the method(s))
- [ ] All tables and figures in the paper
- [x] Selected tables and figures in the paper, as explained and justified below:

Tables and figures for the simulation study are provided, as well as an illustrative analysis on a related dataset. The tables and figures for the primary analysis are not reproducible because the data is private.

## Workflow

### Location

The workflow is available:

- [x] As part of the paper’s supplementary material.
- [x] In this Git repository: www.github.com/theodds/RelSurvBart
- [ ] Other (please specify):

### Format(s)

- [ ] Single master code file 
- [ ] Wrapper (shell) script(s)
- [ ] Self-contained R Markdown file, Jupyter notebook, or other literate programming approach
- [x] Text file (e.g., a readme-style file) that documents workflow
- [ ] Makefile
- [ ] Other (more detail in *Instructions* below)

### Instructions

Detailed instructions are given in the file README.md. Individual scripts reproducing results are given in the folder `Code/src/` and are numbered in the order they should be run; all of them can be run by running the file `Code/main.R`. Markdown files are given in Code/Markdown

### Expected run-time

Approximate time needed to reproduce the analyses on a standard desktop machine:

- [ ] < 1 minute
- [ ] 1-10 minutes
- [ ] 10-60 minutes
- [x] 1-8 hours
- [ ] > 8 hours
- [ ] Not feasible to run on a desktop machine, as described here:

### Additional information (optional)

# Notes (optional)

