# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eval_loglik <- function(y, delta, lambda, grid, base_haz, cum_base_haz, pop_haz, obs_to_bin) {
    .Call(`_BART4RS_eval_loglik`, y, delta, lambda, grid, base_haz, cum_base_haz, pop_haz, obs_to_bin)
}

