// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eval_loglik
NumericMatrix eval_loglik(NumericVector& y, NumericVector& delta, NumericMatrix& lambda, NumericVector& grid, NumericMatrix& base_haz, NumericMatrix& cum_base_haz, NumericVector& pop_haz, std::vector<int>& obs_to_bin);
RcppExport SEXP _BART4RS_eval_loglik(SEXP ySEXP, SEXP deltaSEXP, SEXP lambdaSEXP, SEXP gridSEXP, SEXP base_hazSEXP, SEXP cum_base_hazSEXP, SEXP pop_hazSEXP, SEXP obs_to_binSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type base_haz(base_hazSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type cum_base_haz(cum_base_hazSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type pop_haz(pop_hazSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type obs_to_bin(obs_to_binSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_loglik(y, delta, lambda, grid, base_haz, cum_base_haz, pop_haz, obs_to_bin));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_stan_fit4PEHaz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4WeibHaz_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_BART4RS_eval_loglik", (DL_FUNC) &_BART4RS_eval_loglik, 8},
    {"_rcpp_module_boot_stan_fit4PEHaz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4PEHaz_mod, 0},
    {"_rcpp_module_boot_stan_fit4WeibHaz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4WeibHaz_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_BART4RS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
